#pragma once

#include <AzCore/Component/Entity.h>
#include <AzCore/Math/Quaternion.h>
#include <AzCore/Math/Transform.h>
#include <AzCore/Math/Vector3.h>
#include <AzFramework/Physics/Material/PhysicsMaterialSlots.h>
#include <AzFramework/Physics/Shape.h>
#include <AzFramework/Physics/ShapeConfiguration.h>
#include <AzCore/std/optional.h>

#include <Jolt/Jolt.h>
#include "Jolt/Math/Vec3.h"
// #include <Jolt/Physics/Collision/ObjectLayer.h>
#include "Jolt/Physics/Collision/Shape/Shape.h"
#include "Jolt/Physics/Collision/Shape/BoxShape.h"
#include "Jolt/Physics/Collision/Shape/CapsuleShape.h"
// #include "Jolt/Physics/Collision/Shape/DecoratedShape.h"
#include "Jolt/Physics/Collision/Shape/HeightFieldShape.h"
// #include "Jolt/Physics/Collision/Shape/MeshShape.h"
// #include "Jolt/Physics/Collision/Shape/PlaneShape.h"
#include "Jolt/Physics/Collision/Shape/SphereShape.h"
// #include "Jolt/Physics/SoftBody/SoftBodyShape.h"
#include <Jolt/Physics/Collision/Shape/RotatedTranslatedShape.h>

namespace AzPhysics
{
    class CollisionGroup;
    struct RigidBodyConfiguration;
    struct StaticRigidBodyConfiguration;
    struct StaticRigidBody;
    class Scene;
}

namespace Physics
{
    class RigidBodyConfiguration;
    class ColliderConfiguration;
    class ShapeConfiguration;
}

namespace JPH
{
    // class Shape;
    class BroadPhaseLayer;
}

namespace JoltPhysics
{
    class BodyData;
    class JoltPhysicsMaterial;

    namespace Pipeline
    {
        class MeshAssetData;
    } // namespace Pipeline

    namespace Utils
    {
        AzPhysics::Scene* GetDefaultScene();

        AZStd::optional<Physics::CookedMeshShapeConfiguration> CreateConvexFromPrimitive(
            const Physics::ColliderConfiguration& colliderConfig,
            const Physics::ShapeConfiguration& primitiveShapeConfig, AZ::u8 subdivisionLevel, const AZ::Vector3& scale);

        //! Returns whether a shape configuration describes a primitive shape such as a box or sphere, as opposed to mesh geometry.
        bool IsPrimitiveShape(const Physics::ShapeConfiguration& shapeConfig);

        //! Minimum and maximum values for the level of subdivision used when approximating capsules and spheres with convex meshes.
        //! The maximum value is chosen so that the number of faces and vertices generated by CreateConvexFromPrimitive will be within
        //! the limit imposed by PhysX (255).
        //! @{
        constexpr AZ::u8 MinCapsuleSubdivisionLevel = 1;
        constexpr AZ::u8 MaxCapsuleSubdivisionLevel = 5;
        //! @}

        // 255 is the hard limit for PhysX number of vertices/faces. Upper bound is set to something sensible and less than this hard limit.
        constexpr AZ::u8 MinFrustumSubdivisions = 3;
        constexpr AZ::u8 MaxFrustumSubdivisions = 125;

        //! Creates the points for a given frustum along the z axis as specified by the supplied arguements.
        //!
        //! @param height Height of the frustum. Must be greater than 0.
        //! @param bottomRadius Radius of bottom cace of frustum. Must be greater than 0 if topRadius is 0, otherwise can be 0.
        //! @param topRadius Radius of top face of frustum. Must be greater than 0 if bottompRadius is 0, otherwise can be 0.
        //! @param subdivisionsNumber of angular subdivisions. Must be between 3 and 125 inclusive.
        //! @return Either a valid point list or none if any of the arguements are invalid.
        //!
        AZStd::optional<AZStd::vector<AZ::Vector3>> CreatePointsAtFrustumExtents(float height, float bottomRadius, float topRadius, AZ::u8 subdivisions);

        //! Creates a Jolt cooked mesh config from the given points.
        //!
        //! @param points Vector of points to build the mesh from.
        //! @param scale Scale to be assigned to the cooked mesh.
        //! @return Either a valid cooked mesh or none if the cooking failed.
        //!
        AZStd::optional<Physics::CookedMeshShapeConfiguration> CreateJoltCookedMeshConfiguration(const AZStd::vector<AZ::Vector3>& points, const AZ::Vector3& scale);

        // JPH::ShapeSettings* CreateJoltShapeSettingsFromConfig(const Physics::ShapeConfiguration& shapeConfiguration);

        JPH::Shape* CreateJoltShapeFromConfig(
            const Physics::ColliderConfiguration& colliderConfiguration,
            const Physics::ShapeConfiguration& shapeConfiguration
        );

        bool ComputeJoltShapeFromConfig(
            const Physics::ShapeConfiguration& shapeConfiguration,
            JPH::Shape::ShapeResult& outResult,
            AZStd::vector<const JoltPhysicsMaterial*>& inMaterials);

        // void CreateJoltShapeResultFromHeightField(
        //     Physics::HeightfieldShapeConfiguration& heightfieldConfig,
        //     JPH::Shape::ShapeResult& outResult,
        //     AZStd::vector<const JoltPhysicsMaterial*>& inMaterials);

        AZStd::vector<float> ConvertHeightfieldSamples(
            const Physics::HeightfieldShapeConfiguration& heightfield,
            const size_t startCol, const size_t startRow,
            const size_t numColsToUpdate, const size_t numRowsToUpdate);

        AZ::u32 ConstructObjectLayer(
            const AzPhysics::CollisionLayer& assignedCollisionLayer,
            const AzPhysics::CollisionGroup& assignedCollisionGroup,
            const JPH::BroadPhaseLayer& broadPhaseLayer);

        //! Converts collider position and orientation offsets to a transform.
        AZ::Transform GetColliderLocalTransform(const AZ::Vector3& colliderRelativePosition
            , const AZ::Quaternion& colliderRelativeRotation);

        //! Gets the local transform for a collider (the position and rotation relative to its entity).
        AZ::Transform GetColliderLocalTransform(const AZ::EntityComponentIdPair& idPair);

        //! Combines collider position and orientation offsets and world transform to a transform.
        AZ::Transform GetColliderWorldTransform(const AZ::Transform& worldTransform
            , const AZ::Vector3& colliderRelativePosition
            , const AZ::Quaternion& colliderRelativeRotation);

        //! Converts points in a collider's local space to world space positions
        //! accounting for collider position and orientation offsets.
        void ColliderPointsLocalToWorld(AZStd::vector<AZ::Vector3>& pointsInOut
            , const AZ::Transform& worldTransform
            , const AZ::Vector3& colliderRelativePosition
            , const AZ::Quaternion& colliderRelativeRotation
            , const AZ::Vector3& nonUniformScale);

        //! Returns AABB of collider by constructing a JPH::Shape from collider and shape configuration,
        //! and invoking Shape->GetWorldSpaceBounds.
        //! This function is used only by editor components.
        AZ::Aabb GetColliderAabb(const AZ::Transform& worldTransform
            , bool hasNonUniformScale
            , AZ::u8 subdivisionLevel
            , const ::Physics::ShapeConfiguration& shapeConfiguration
            , const ::Physics::ColliderConfiguration& colliderConfiguration);

        bool TriggerColliderExists(AZ::EntityId entityId);

        void CreateShapesFromAsset(const Physics::PhysicsAssetShapeConfiguration& assetConfiguration,
            const Physics::ColliderConfiguration& originalColliderConfiguration, bool hasNonUniformScale,
            AZ::u8 subdivisionLevel, AZStd::vector<AZStd::shared_ptr<Physics::Shape>>& resultingShapes);

        void GetColliderShapeConfigsFromAsset(const Physics::PhysicsAssetShapeConfiguration& assetConfiguration,
            const Physics::ColliderConfiguration& originalColliderConfiguration,
            bool hasNonUniformScale, AZ::u8 subdivisionLevel, AzPhysics::ShapeColliderPairList& resultingColliderShapes);

        //! Gets the scale from the entity's Transform component.
        float GetTransformScale(AZ::EntityId entityId);
        //! Returns a vector scale with each element equal to the max element from the entity's Transform component.
        AZ::Vector3 GetUniformScale(AZ::EntityId entityId);
        //! Gets the scale from the entity's Non-Uniform Scale component, if it is present.
        //! Otherwise (1, 1, 1) is returned.
        AZ::Vector3 GetNonUniformScale(AZ::EntityId entityId);
        //! Gets the overall scale, taking into account the scale from both the entity's Transform component and the
        //! Non-Uniform Scale component, if it is present.
        AZ::Vector3 GetOverallScale(AZ::EntityId entityId);

        namespace Geometry
        {
            using PointList = AZStd::vector<AZ::Vector3>;

            //! Generates a list of points on a box.
            PointList GenerateBoxPoints(const AZ::Vector3& min, const AZ::Vector3& max);

            //! Generates a list of points on the surface of a sphere.
            PointList GenerateSpherePoints(float radius);

            //! Generates a list of points on the surface of a cylinder.
            PointList GenerateCylinderPoints(float height, float radius);

            // //! Generates vertices and indices representing the provided box geometry
            // void GetBoxGeometry(const physx::PxBoxGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices, AZStd::vector<AZ::u32>& indices);
            //
            // //! Generates vertices and indices representing the provided capsule geometry
            // void GetCapsuleGeometry(const physx::PxCapsuleGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices, AZStd::vector<AZ::u32>& indices, const AZ::u32 stacks, const AZ::u32 slices);
            //
            // //! Generates vertices and indices representing the provided convex mesh geometry
            // void GetConvexMeshGeometry(const physx::PxConvexMeshGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices, AZStd::vector<AZ::u32>& indices);
            //
            // //! Generates vertices and indices representing the provided heightfield geometry, optionally limited to a bounding box
            // void GetHeightFieldGeometry(const physx::PxHeightFieldGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices,
            //     AZStd::vector<AZ::u32>& indices, const AZ::Aabb* optionalBounds);
            //
            // //! Generates vertices and indices representing the provided sphere geometry and optional stacks and slices
            // void GetSphereGeometry(const physx::PxSphereGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices, AZStd::vector<AZ::u32>& indices, const AZ::u32 stacks, const AZ::u32 slices);
            //
            // //! Generates vertices and indices representing the provided triangle mesh geometry
            // void GetTriangleMeshGeometry(const physx::PxTriangleMeshGeometry& geometry, AZStd::vector<AZ::Vector3>& vertices, AZStd::vector<AZ::u32>& indices);
        } // namespace Geometry
    } // namespace Utils
}
